image: endle/wine-on-drone

script:
  - sudo add-apt-repository -y ppa:ubuntu-wine/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y binutils-mingw-w64-i686
  - sudo apt-get install -y gcc-mingw-w64-i686
  - sudo apt-get install -y wine1.7
  - sudo apt-get install -y binfmt-support
  - sudo apt-get install -y libxml2-dev libc6-dev
  - sudo apt-get build-dep -y python-all python-all-dev
  - sudo apt-get build-dep -y libxml2-dev libc6-dev
  - cd code
  - unset CC
  - sudo update-binfmts --disable wine
  - export ARCH=i486
  - ./autogen.sh  --host=i686-w64-mingw32 --build=x86_64-pc-linux --without-python CPPFLAGS="${CPPFLAGS} -I/usr/include/x86_64-linux-gnu"
  - make

